routes/web.php
<?php

Route::get('/', 'MainController@index')->name('main');

Route::get('/categories', 'ProductController@categories')->name('categories');


//Корзина
Route::group(['prefix' => 'cart'] , function () {
    Route::post('/add/{id}', 'CartController@cartAdd')->name('cart-add');

    Route::group(['middleware' => 'cartIsNotEmpty'],
        function () {
            Route::get('/', 'CartController@cart')->name('cart');
            Route::post('/confirm', 'CartController@cartСonfirm')->name('cart-confirm');
            Route::post('/remove/{id}', 'CartController@cartRemove')->name('cart-remove');
        });
});

//Вывод категорий, товаров опред категор, карточка продукта в категории
Route::get('/categories/{category}', 'ProductController@category')->name('category');
Route::get('/categories/{category}/{product?}', 'ProductController@showproduct')->name('product');

//Работа с профилем
Route::get('/profile', 'ProfileController@index')->name('profile.profile');
Route::get('/profile/edit','ProfileController@getEdit')->name('profile.edit');
Route::post('/profile/edit','ProfileController@postEdit')->name('profile.edit');

//Админка
Route::group(['middleware' => ['auth','isAdmin'], 'namespace' => 'Admin'], function () {
    Route::get('/adminPanel','AdminController@index')->name('adminPanel');
    Route::resource('/adminPanel/Category','CategoryController');
    Route::resource('/adminPanel/Payments','PaymentsController');
    Route::resource('/adminPanel/Manufacturers','ManufacturersController');
    Route::resource('/adminPanel/Deliveries','DeliveriesController');
    Route::resource('/adminPanel/Products','ProductsController');
    Route::resource('/adminPanel/Orders','OrdersController');
    Route::resource('/adminPanel/Users','UsersController');
});


//Аунтефикация
Auth::routes();
Route::get('signinup','MainController@signinup')->name('sign');
//Route::get('/home', 'HomeController@index')->name('home');

resources/views/Admins/adminPanel.blade.php
@extends('layouts.master')
@section('title','Админ панель')
@section('content')
    <section class="admin-panel text-c">
        <h3>Добро пожаловать, вы зашли в панель администратора</h3>
        <h4>Выберите нужную таблицу, для работы с ней:</h4>
        <ul>
            <li><a href="{{ route('Category.index')}}">Категории</a></li>
            <li><a href="{{ route('Deliveries.index') }}">Способы доставки</a></li>
            <li><a href="{{ route('Payments.index') }}">Способы оплаты</a></li>
            <li><a href="{{ route('Manufacturers.index') }}">Производители</a></li>
            <li><a href="{{ route('Products.index') }}">Товары</a></li>
            <li><a href="{{ route('Orders.index') }}">Заказы</a></li>
            <li><a href="{{ route('Users.index') }}">Пользователи</a></li>
        </ul>
    </section>
@endsection