routes/web.php
<?php

Route::get('/', 'MainController@index')->name('main');

Route::get('/categories', 'ProductController@categories')->name('categories');


//Корзина
Route::group(['prefix' => 'cart'] , function () {
    Route::post('/add/{id}', 'CartController@cartAdd')->name('cart-add');

    Route::group(['middleware' => 'cartIsNotEmpty'],
        function () {
            Route::get('/', 'CartController@cart')->name('cart');
            Route::post('/confirm', 'CartController@cartСonfirm')->name('cart-confirm');
            Route::post('/remove/{id}', 'CartController@cartRemove')->name('cart-remove');
        });
});

//Вывод категорий, товаров опред категор, карточка продукта в категории
Route::get('/categories/{category}', 'ProductController@category')->name('category');
Route::get('/categories/{category}/{product?}', 'ProductController@showproduct')->name('product');

//Работа с профилем
Route::get('/profile', 'ProfileController@index')->name('profile.profile');
Route::get('/profile/edit','ProfileController@getEdit')->name('profile.edit');
Route::post('/profile/edit','ProfileController@postEdit')->name('profile.edit');

//Админка
Route::group(['middleware' => ['auth','isAdmin'], 'namespace' => 'Admin'], function () {
    Route::get('/adminPanel','AdminController@index')->name('adminPanel');
    Route::resource('/adminPanel/Category','CategoryController');
    Route::resource('/adminPanel/Payments','PaymentsController');
    Route::resource('/adminPanel/Manufacturers','ManufacturersController');
    Route::resource('/adminPanel/Deliveries','DeliveriesController');
    Route::resource('/adminPanel/Products','ProductsController');
    Route::resource('/adminPanel/Orders','OrdersController');
    Route::resource('/adminPanel/Users','UsersController');
});


//Аунтефикация
Auth::routes();
Route::get('signinup','MainController@signinup')->name('sign');
//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Manufacturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    protected $fillable = [
      'name'
    ];

    public function products() {
        return $this->hasMany(Tovar::class);
    }
}

app/Http/Controllers/Admin/ManufacturersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Manufacturer;
use Illuminate\Http\Request;

class ManufacturersController extends Controller
{
    public function index() {
        $manufacturers = Manufacturer::all();

        return view('Admins.Manufacturers.index', compact('manufacturers'));
    }

    public function create() {
        return view('Admins.Manufacturers.create');
    }

    public function store(Request $request) {
        $request->validate([
            'name' => 'required'
        ]);

        $manufacturer = new Manufacturer([
            'name' => $request->get('name')
        ]);
        $manufacturer->save();

        return redirect('/adminPanel/Manufacturers')->with('success','Производитель был добавлен');
    }

    public function show($id) {

        $manufacturer = Manufacturer::find($id);
        return view('Admins.Manufacturers.show', compact('manufacturer'));
    }

    public function edit($id) {
        $manufacturer = Manufacturer::find($id);

        return view('Admins.Manufacturers.edit',compact('manufacturer'));
    }

    public function update(Request $request, $id) {
        $request->validate([
            'name' => 'required'
        ]);

        $manufacturer = Manufacturer::find($id);
        $manufacturer->name = $request->get('name');
        $manufacturer->save();

        return redirect('/adminPanel/Manufacturers')->with('success','Производитель был изменен');
    }

    public function destroy($id) {
        $manufacturer = Manufacturer::find($id);
        $manufacturer->delete();

        return redirect('/adminPanel/Manufacturers')->with('success','Производитель был удалён');
    }
}

resources/views/Admins/Manufacturers/create.blade.php
@extends('layouts.master')
@section('title','Добавить производителя')
@section('content')
    <section class="flex flex-col items-center mt-6 gap-2">
        <form action="{{ route('Manufacturers.store') }}" method="post" class="flex flex-col gap-1">
            @csrf
            <label for="">Производитель:</label>
            <input type="text" name="name" value="{{ old('name') }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <button type="submit" class="text-white mt-3 text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:shadow-lg">Создать</button>
            <a href="{{ route('Manufacturers.index') }}" class="text-center hover:text-blue-500">Вернуться обратно</a>
        </form>
    </section>
@endsection

resources/views/Admins/Manufacturers/edit.blade.php
@extends('layouts.master')
@section('title','Редактировать производителя'.$manufacturer->id)
@section('content')
    <section class="flex flex-col items-center mt-6 gap-2">
        <form action="{{ route('Manufacturers.update', $manufacturer) }}" method="post" class="flex flex-col gap-1">
            @csrf
            @method('PATCH')
            <label for="">Производитель:</label>
            <input type="text" name="name" value="{{ $manufacturer->name }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <button type="submit" class="text-white mt-3 text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:shadow-lg">Изменить</button>
            <a href="{{ route('Manufacturers.index') }}" class="text-center hover:text-blue-500">Вернуться обратно</a>
        </form>
    </section>
@endsection

resources/views/Admins/Manufacturers/index.blade.php
@extends('layouts.master')
@section('title','Все производители')
@section('content')
    <section class="overflow-x-auto">
        <div class="flex flex-col items-center">
            <a class="mt-6 hover:text-blue-500" href="{{ route('adminPanel') }}">Вернуться в админ панель</a>
            <button type="button" class="text-white mt-6 text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg">
                <a href="{{ route('Manufacturers.create') }}">Добавить производителя</a></button>
            @if(session()->get('success'))
                <div class="py-3 px-2 my-2 bg-yellow-300 text-yellow-800 rounded border border-yellow-600" role="alert">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="min-w-screen min-h-screen flex justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                            <th class="py-3 px-6 text-center">№</th>
                            <th class="py-3 px-6 text-center">Наименование организации</th>
                            <th class="py-3 px-6 text-center">Действия</th>
                        </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                        @foreach($manufacturers as $manufacturer)
                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-center">
                                    <span>{{ $manufacturer->id }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <span>{{ $manufacturer->name }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">
                                        <a href="{{ route('Manufacturers.edit',$manufacturer) }}">
                                            <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                </svg>
                                            </div>
                                        </a>
                                        <form action="{{ route('Manufacturers.destroy', $manufacturer) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button>
                                                <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </div>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection