routes/web.php
<?php

Route::get('/', 'MainController@index')->name('main');

Route::get('/categories', 'ProductController@categories')->name('categories');


//Корзина
Route::group(['prefix' => 'cart'] , function () {
    Route::post('/add/{id}', 'CartController@cartAdd')->name('cart-add');

    Route::group(['middleware' => 'cartIsNotEmpty'],
        function () {
            Route::get('/', 'CartController@cart')->name('cart');
            Route::post('/confirm', 'CartController@cartСonfirm')->name('cart-confirm');
            Route::post('/remove/{id}', 'CartController@cartRemove')->name('cart-remove');
        });
});

//Вывод категорий, товаров опред категор, карточка продукта в категории
Route::get('/categories/{category}', 'ProductController@category')->name('category');
Route::get('/categories/{category}/{product?}', 'ProductController@showproduct')->name('product');

//Работа с профилем
Route::get('/profile', 'ProfileController@index')->name('profile.profile');
Route::get('/profile/edit','ProfileController@getEdit')->name('profile.edit');
Route::post('/profile/edit','ProfileController@postEdit')->name('profile.edit');

//Админка
Route::group(['middleware' => ['auth','isAdmin'], 'namespace' => 'Admin'], function () {
    Route::get('/adminPanel','AdminController@index')->name('adminPanel');
    Route::resource('/adminPanel/Category','CategoryController');
    Route::resource('/adminPanel/Payments','PaymentsController');
    Route::resource('/adminPanel/Manufacturers','ManufacturersController');
    Route::resource('/adminPanel/Deliveries','DeliveriesController');
    Route::resource('/adminPanel/Products','ProductsController');
    Route::resource('/adminPanel/Orders','OrdersController');
    Route::resource('/adminPanel/Users','UsersController');
});


//Аунтефикация
Auth::routes();
Route::get('signinup','MainController@signinup')->name('sign');
//Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Catproduct;
use App\Models\Manufacturer;
use App\Models\Payment;
use App\Models\Tovar;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    public function index() {
        $products = Tovar::all();
        return view('Admins.Products.index', compact('products'));
    }

    public function create() {

        $categories = Catproduct::all();
        $manufacturers = Manufacturer::all();

        return view('Admins.Products.create', compact('categories', 'manufacturers'));
    }

        public function store(Request $request) {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'count' => 'required',
            'manufacturer' => 'required',
            'category' => 'required',
            'description' => 'string'
//            'photo' => 'required',
        ]);

        $product = new Tovar([
            'name' => $request->get('name'),
            'price' => $request->get('price'),
            'count' => $request->get('count'),
            'manufacturer_id' => $_POST["manufacturer"],
            'catproduct_id' => $_POST["category"],
            'description' => $_POST['description']
        ]);
        $product->save();

        return redirect('/adminPanel/Products')->with('success','Товар был добавлен');
    }

    public function show($id) {

        $product = Tovar::find($id);
        $images = Tovar::find($id)->Images;

        return view('Admins.Products.show', compact('product','images'));
    }

    public function edit($id) {
        $product = Tovar::find($id);
        $categories = Catproduct::all();
        $manufacturers = Manufacturer::all();

        return view('Admins.Products.edit',compact('product','categories','manufacturers'));
    }

    public function update(Request $request, $id) {
        $request->validate([
            'name' => '',
            'price' => '',
            'count' => '',
            'manufacturer' => '',
            'category' => '',
            'description' => 'string'
        ]);

        $product = Tovar::find($id);
        $product->name = $request->get('name');
        $product->price = $request->get('price');
        $product->count = $request->get('count');
        $product->manufacturer_id = $_POST["manufacturer"];
        $product->catproduct_id = $_POST["category"];
        $product->description = $_POST['description'];
        $product->save();

        return redirect('/adminPanel/Products')->with('success','Товар был изменен');
    }

    public function destroy($id) {
        $product = Tovar::find($id);
        $product->delete();

        return redirect('/adminPanel/Products')->with('success','Товар был удален');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Catproduct;
use App\Models\Image;
use App\Models\Tovar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    public function showproduct($category_alias,$id = null)
    {
        $product = Tovar::where('id',$id)->first();
        $images = Tovar::find($id)->Images;

        return view('product',compact('images','product'));
    }

    public function categories() {
        return view('categories');
    }

    public function category($category_alias) {
        $category = Catproduct::where('alias',$category_alias)->first();
        $count = DB::selectOne("Select ProductCountCategory(?) as count",[$category->id]);
        return view('category',compact('category', 'count'));
    }


}

resources/views/Admins/Products/create.blade.php
@extends('layouts.master')
@section('title','Добавить товар')
@section('content')
    <form action="{{ route('Products.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <label for="">Название товара</label>
        <input type="text" name="name">
        <label for="">Цена</label>
        <input type="text" name="price">
        <label for="">Количество</label>
        <input type="text" name="count">
        <label for="">Производитель</label>
        <select name="manufacturer">
            @foreach($manufacturers as $manufacturer)
                <option value="{{ $manufacturer->id }}">{{ $manufacturer->name }}</option>
            @endforeach
        </select>
        <label for="">Категория</label>
        <select name="category">
            @foreach($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
        <label for="">Фотография</label>
        <input type="file" name="photo">
        <label for="">Описание товара</label>
        <textarea name="description" cols="30" rows="10"></textarea>
        <button type="submit">Создать</button>
    </form>
    <a href="{{ route('Products.index') }}">Вернуться обратно</a>
@endsection

resources/views/Admins/Products/edit.blade.php
@extends('layouts.master')
@section('title','Редактировать товар'.$product->id)
@section('content')
    <form action="{{ route('Products.update', $product) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <label for="">Название товара:</label>
        <input type="text" name="name" value="{{ $product->name }}">
        <label for="">Цена</label>
        <input type="text" name="price" value="{{ $product->price }}">
        <label for="">Количество</label>
        <input type="text" name="count" value="{{ $product->count }}">
        <label for="">Производитель</label>
        <select name="manufacturer">
            @foreach($manufacturers as $manufacturer)
                <option value="{{ $manufacturer->id }}">{{ $manufacturer->name }}</option>
            @endforeach
        </select>
        <label for="">Категория</label>
        <select name="category">
            @foreach($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
        <label for="">Фотография</label>
        <img src="{{ Storage::url($product->preview) }}" alt="">
        <input type="file" name="photo">
        <label for="">Описание</label>
        <textarea name="description" id="" cols="30" rows="10">{!! $product->description !!}</textarea>
        <button type="submit">Изменить товар</button>
    </form>
@endsection

resources/views/Admins/Products/index.blade.php
@extends('layouts.master')
@section('title','Все товары')
@section('content')
    <section class="overflow-x-auto">
        <div class="flex flex-col items-center">
            <a class="mt-6 hover:text-blue-500" href="{{ route('adminPanel') }}">Вернуться в админ панель</a>
            <button type="button" class="text-white mt-6 text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg">
                <a href="{{ route('Products.create') }}">Создать товар</a></button>
            @if(session()->get('success'))
                <div class="py-3 px-2 my-2 bg-green-300 text-green-800 rounded border border-green-600" role="alert">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="min-w-screen min-h-screen flex justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                            <th class="py-3 px-6 text-left">№</th>
                            <th class="py-3 px-6 text-left">Название</th>
                            <th class="py-3 px-6 text-center">Цена</th>
                            <th class="py-3 px-6 text-center">Производитель</th>
                            <th class="py-3 px-6 text-center">Категория</th>
                            <th class="py-3 px-6 text-center">Действия</th>
                        </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                        @foreach($products as $product)
                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left">
                                    <span>{{ $product->id }}</span>
                                </td>
                                <td class="py-3 px-6 text-left">
                                    <span>{{ $product->name }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <span>{{ $product->price }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <span>{{ $product->manufacturer->name }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <span>{{ App\Models\Catproduct::find($product->catproduct_id)->value('name') }}</span>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">
                                        <a href="{{ route('Products.show', $product) }}">
                                            <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                                </svg>
                                            </div>
                                        </a>
                                        <a href="{{ route('Products.edit',$product) }}">
                                            <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                </svg>
                                            </div>
                                        </a>
                                        <form action="{{ route('Products.destroy', $product) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button>
                                                <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </div>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Admins/Products/show.blade.php
@extends('layouts.master')
@section('title','Просмотр товара'.$product->id)
@section('content')
    <section>
        <h3>{{ $product->name }}</h3>
        <span>{{ $product->price }}</span>
        <span>{{ $product->count }}</span>
        <span>{{ $product->manufacturer->name }}</span>
        <span> {{ App\Models\Catproduct::find($product->catproduct_id)->value('name') }}</span>
        @foreach($images as $image)
            <img src="{{ Storage::url($image->photo) }}" alt="">
        @endforeach
        <textarea name="description" cols="30" rows="10">{!! $product->description !!}</textarea>
        <a href="{{ route('Products.index') }}">Вернуться обратно</a>
    </section>
@endsection