routes/web.php
<?php

Route::get('/', 'MainController@index')->name('main');

Route::get('/categories', 'ProductController@categories')->name('categories');


//Корзина
Route::group(['prefix' => 'cart'] , function () {
    Route::post('/add/{id}', 'CartController@cartAdd')->name('cart-add');

    Route::group(['middleware' => 'cartIsNotEmpty'],
        function () {
            Route::get('/', 'CartController@cart')->name('cart');
            Route::post('/confirm', 'CartController@cartСonfirm')->name('cart-confirm');
            Route::post('/remove/{id}', 'CartController@cartRemove')->name('cart-remove');
        });
});

//Вывод категорий, товаров опред категор, карточка продукта в категории
Route::get('/categories/{category}', 'ProductController@category')->name('category');
Route::get('/categories/{category}/{product?}', 'ProductController@showproduct')->name('product');

//Работа с профилем
Route::get('/profile', 'ProfileController@index')->name('profile.profile');
Route::get('/profile/edit','ProfileController@getEdit')->name('profile.edit');
Route::post('/profile/edit','ProfileController@postEdit')->name('profile.edit');

//Админка
Route::group(['middleware' => ['auth','isAdmin'], 'namespace' => 'Admin'], function () {
    Route::get('/adminPanel','AdminController@index')->name('adminPanel');
    Route::resource('/adminPanel/Category','CategoryController');
    Route::resource('/adminPanel/Payments','PaymentsController');
    Route::resource('/adminPanel/Manufacturers','ManufacturersController');
    Route::resource('/adminPanel/Deliveries','DeliveriesController');
    Route::resource('/adminPanel/Products','ProductsController');
    Route::resource('/adminPanel/Orders','OrdersController');
    Route::resource('/adminPanel/Users','UsersController');
});


//Аунтефикация
Auth::routes();
Route::get('signinup','MainController@signinup')->name('sign');
//Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Catproduct;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index() {
        $categories = Catproduct::all();

        return view('Admins.Categories.index', compact('categories'));
    }

    public function create() {
        return view('Admins.Categories.create');
    }

    public function store(Request $request) {
        $request->validate([
            'category-name' => 'required',
            'photo' => 'required',
            'alias' => 'required'
        ]);

        $category = new Catproduct([
            'name' => $request->get('category-name'),
            'photo' => $request->file('photo')->store('category'),
            'alias' => $request->get('alias')
        ]);
        $category->save();

        return redirect('/adminPanel/Category')->with('success','Категория была добавлена');
    }

    public function show($id) {

        $category = Catproduct::find($id);
        return view('Admins.Categories.show', compact('category'));
    }

    public function edit($id) {
        $category = Catproduct::find($id);

        return view('Admins.Categories.edit',compact('category'));
    }

    public function update(Request $request, $id) {
        $request->validate([
            'category-name' => 'required',
            'alias' => 'required'
        ]);

        $category = Catproduct::find($id);
        $category->name = $request->get('category-name');
        $category->photo = $request->file('photo')->store('category');
        $category->alias = $request->get('alias');
        $category->save();

        return redirect('/adminPanel/Category')->with('success','Категория была изменена');
    }


    public function destroy($id) {
        $category = Catproduct::find($id);
        $category->delete();

        return redirect('/adminPanel/Category')->with('success','Категория была удалена');
    }
}

resources/views/Admins/Categories/create.blade.php
@extends('layouts.master')
@section('title','Добавить категорию')
@section('content')
    <section class="flex flex-col items-center mt-6 gap-2">
        <form action="{{ route('Category.store') }}" method="post" enctype="multipart/form-data" class="flex flex-col gap-1">
            @csrf
            <label for="">Название категории:</label>
            <input type="text" name="category-name" value="{{ old('category-name') }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <label for="">Фотография</label>
            <input type="file" name="photo">
            <label for="">Алиас</label>
            <input type="text" name="alias" value="{{ old('alias') }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <button type="submit" class="text-white mt-3 text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:shadow-lg">Создать</button>
        </form>
        <a href="{{ route('Category.index') }}" class="text-center hover:text-blue-500">Вернуться обратно</a>
    </section>
@endsection

resources/views/Admins/Categories/edit.blade.php
@extends('layouts.master')
@section('title','Редактировать категорию'.$category->id)
@section('content')
    <section class="flex flex-col items-center mt-6 gap-2">
        <form action="{{ route('Category.update', $category) }}" method="post" enctype="multipart/form-data" class="flex flex-col gap-1">
            @csrf
            @method('PATCH')
            <label for="">Название категории:</label>
            <input type="text" name="category-name" value="{{ $category->name }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <label for="">Фотография</label>
            <img src="{{ Storage::url($category->photo) }}" alt="" >
            <input type="file" name="photo">
            <label for="">Алиас</label>
            <input type="text" name="alias" value="{{ $category->alias }}" class="border border-gray-300 p-2 my-2 rounded-md focus:outline-none focus:ring-2 ring-blue-200">
            <button type="submit" class="text-white mt-3 text-sm py-2.5 px-5 rounded-md bg-blue-500 hover:shadow-lg">Изменить категорию</button>
        </form>
        <a href="{{ route('Category.index') }}" class="text-center hover:text-blue-500">Вернуться обратно</a>
    </section>
@endsection

resources/views/Admins/Categories/index.blade.php
@extends('layouts.master')
@section('title','Все категории')
@section('content')
    <section class="overflow-x-auto">
        <div class="flex flex-col items-center">
            <a class="mt-6 hover:text-blue-500" href="{{ route('adminPanel') }}">Вернуться в админ панель</a>
            <button type="button" class="text-white mt-6 text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg"><a href="{{ route('Category.create') }}">Создать категорию</a></button>
            @if(session()->get('success'))
                <div class="py-3 px-2 my-2 bg-yellow-300 text-yellow-800 rounded border border-yellow-600" role="alert">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="min-w-screen min-h-screen flex justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                            <th class="py-3 px-6 text-left">№</th>
                            <th class="py-3 px-6 text-left">Название</th>
                            <th class="py-3 px-6 text-center">Фотография</th>
                            <th class="py-3 px-6 text-center">Алиас</th>
                            <th class="py-3 px-6 text-center">Действия</th>
                        </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                        @foreach($categories as $category)
                        <tr class="border-b border-gray-200 hover:bg-gray-100">
                            <td class="py-3 px-6 text-left">
                                <span>{{ $category->id }}</span>
                            </td>
                            <td class="py-3 px-6 text-left">
                                <span>{{ $category->name }}</span>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <div class="flex items-center justify-center">
                                    <img class="w-10 h-10 transform hover:scale-125" src="{{ Storage::url($category->photo) }}"/>
                                </div>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <span>{{ $category->alias }}</span>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <div class="flex item-center justify-center">
                                    <a href="{{ route('Category.show', $category) }}">
                                        <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </div>
                                    </a>
                                    <a href="{{ route('Category.edit',$category) }}">
                                        <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </div>
                                    </a>
                                    <form action="{{ route('Category.destroy', $category) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button>
                                            <div class="w-6 mr-2 transform hover:text-blue-500 hover:scale-110">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                            </div>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/Admins/Categories/show.blade.php
@extends('layouts.master')
@section('title','Просмотр категории'.$category->id)
@section('content')
    <section class="w-4/5 mx-auto">
        <div class="flex justify-center flex-col sm:flex-row">
            <div class="sm:w-1/4 p-2">
                <div class="bg-white px-6 py-8 rounded-lg shadow-lg text-center">
                    <div class="mb-3">
                        <img class="w-auto mx-auto" src="{{ Storage::url($category->photo) }}" alt="{{ $category->name }}">
                    </div>
                    <h2 class="text-xl font-medium text-gray-700">{{ $category->name }}</h2>
                    <span class="text-gray-500 block mb-5">{{ $category->alias }}</span>
                </div>
                <a href="{{ route('Category.index') }}" class="text-center hover:text-blue-500">Вернуться обратно</a>
            </div>
        </div>
    </section>
@endsection